import ContentBox from '@/components/content-box'
import code from '../../../../public/services/articles/code.png'
import dns from '../../../../public/services/articles/dns.png'
import cyDns from '../../../../public/services/articles/cy-dns.png'
import binary from '../../../../public/services/articles/binary.png'
import AnimateBlur from '@/components/animate-blur'
import Image from 'next/image'
import Container from '@/components/container'

export default function DnsFilteringGateway() {
  return (
    <Container global>
      <ContentBox
        caption='Easy and affordable solution to control DNS traffic'
        title='DNS Filtering'
        image={code}
      >
        <p>
          DNS filtering is the process of using the Domain Name System (DNS) to
          block malicious websites and filter out harmful or inappropriate
          content. This ensures that your company data remains secure and allows
          companies to have control over what their employees can access on the
          Internet. DNS filtering is often part of a larger access control and
          security strategy. <br /> <br /> Our service allows you to create a
          detailed policy for your users to control Internet access and block
          access to malicious domains in your organization. Comprehensive
          reporting allows you to see Internet activity in real time and also
          use a large number of predefined reports on Internet usage. The
          cloud-based solution checks all your DNS requests against a predefined
          policy, thereby allowing or blocking access to the requested domain.
        </p>
      </ContentBox>
      <ContentBox
        caption='Benefits from additional control and prevention'
        title='Why you need DNS filtering'
      >
        <p>
          The Internet is critical to most businesses these days. Unfortunately,
          malicious websites, spyware and viruses are real business threats that
          simply cannot be ignored. In addition, there is a growing need for
          companies to filter content to protect their employees from risky and
          unnecessary content or to reduce unnecessary costs of Internet traffic
          unrelated to their work needs. <br /> <br /> Our cloud DNS filtering
          solution protects organizations from threats by managing
          organizations’ DNS traffic. It can regulate the content that employees
          can access, protect the network from malware and malicious online
          threats, and control the use of sites that are not compatible with the
          employees’ work. The basic configuration for customers requires no
          software installation and can be set up and running in minutes, making
          it an ideal solution for any organization.
        </p>
      </ContentBox>

      <ContentBox
        caption='Extremely easy to deploy and manage'
        title='How does the system work?'
      >
        <AnimateBlur>
          <Image
            src={dns}
            alt='DNS Gateway'
            className='mx-auto w-full max-w-[1040px]'
          />
        </AnimateBlur>
      </ContentBox>

      <ContentBox
        caption='Extremely easy to deploy and manage'
        title='How does the system work?'
      >
        <div className='flex flex-col lg:flex-row gap-4 lg:ml-[96px]'>
          <div className='flex flex-col gap-4'>
            <AnimateBlur>
              <Image src={cyDns} alt='DNS' className='w-full max-w-[740px]' />
            </AnimateBlur>
            <div className='flex flex-col md:flex-row  gap-4  md:gap-24   md:justify-between '>
              <div>
                <h5>It is used to detect:</h5>
                <ul>
                  <li>Compromised systems</li>
                  <li>Exfiltration of data to C2 servers</li>
                  <li>Malware and phishing attempts</li>
                  <li>Domains generated by an algorithm</li>
                  <li>Domains with spelling errors</li>
                  <li>Malicious network activity</li>
                  <li>Scam websites</li>
                </ul>
              </div>
              <div className='w-[261px]'>
                <h5>It can help with:</h5>
                <ul>
                  <li>Control of employee internet access</li>
                  <li>Reduce the risk of gambling, porn, malicious websites</li>
                  <li>Reducing the risk of phishing and malware/spyware</li>
                  <li>
                    DNS control with whitelists only for critical departments
                  </li>
                  <li>
                    Limit unnecessary services such as social networks and
                    entertainment sites
                  </li>
                  <li>
                    Advanced configuration and policy control on specific
                    employees, branches, and departments
                  </li>
                </ul>
              </div>
            </div>
          </div>
          <AnimateBlur>
            <Image
              src={binary}
              alt='DNS'
              width={222}
              height={412}
              className='max-w-[222px]  mx-auto'
            />
          </AnimateBlur>
        </div>
      </ContentBox>

      <ContentBox
        caption='Huge range of useful functionalities'
        title='Features and capabilities'
      >
        <div className='flex flex-col md:flex-row space-y-4   justify-between '>
          <div className='md:w-1/2 '>
            <ul>
              <li>Malware blocking</li>
              <li>Internet Content Filtering</li>
              <li>Flexible and modular DNS filtering policies</li>
              <li>A more secure policy for BYOD and personal devices</li>
              <li>Fast, reliable and scalable</li>
              <li>Automated usage and blocking reports</li>
              <li>REST API and remote control</li>
              <li>24/7 guaranteed support, management and configuration</li>
            </ul>
          </div>
          <div className='md:w-1/2'>
            <ul>
              <li>Prevention of phishing and malicious domains</li>
              <li>Detection of dangerous services and sites</li>
              <li>Real-time updates</li>
              <li>Protection against Business Email Compromise attacks</li>
              <li>Filter any web content</li>
              <li>Possibilities for integration with external services</li>
              <li>Integration with Active Directory and other MS services</li>
              <li>Access to own web interface for management and monitoring</li>
            </ul>
          </div>
        </div>
      </ContentBox>
    </Container>
  )
}
